name: Only Typescript files allowed
on: [pull_request]

jobs:
  Verify-Changeset-Code-Type:
    name: Check change set do not have javascript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: current
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - name: Print modified files
        run: echo ${{ steps.files.outputs.added_modified }}
      - name: Get extensions of changed files
        if: "contains(format('{0},',steps.files.outputs.added_modified), 'js,')"
        run: |
          echo .js files detected
          exit 1